#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Customize to your needs...
fpath=(
  "$HOME/projects/giantswarm/builder/completion/zsh/"
  "$HOME/projects/giantswarm/primer/completion/zsh/"
  "$HOME/projects/giantswarm/cli/completion/zsh/"
  $fpath
)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
