#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Customize to your needs...
fpath=(
  "$HOME/projects/giantswarm/builder/completion/zsh/"
  "$HOME/projects/giantswarm/primer/completion/zsh/"
  "$HOME/projects/giantswarm/cli/completion/zsh/"
  "$HOME/projects/giantswarm/formica/completion/zsh/"
  "$HOME/projects/private/anna/completion/zsh/"
  "$HOME/projects/private/loader/completion/zsh/"
  $fpath
)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# golang setup
source ${HOME}/.gvm/scripts/gvm
gvm use go1.6 > /dev/null

# Clear right prompt after each command. This prevents copying the command
# indicator (<<<) when copying terminal output.
setopt transientrprompt

# Prevent "zsh: file exists: <file>" warnings when redirecting using >.
setopt clobber

# Show command indicator (<<<) immediatelly (0.1s) after activating it (hitting
# ESC).
export KEYTIMEOUT=1
